# Generated by Django 5.2.8 on 2025-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('X', 'X'), ('XL', 'XL')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('phoneNo', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
